# Generated by Django 5.0.6 on 2024-07-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bot', '0003_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Аватар пользователя'),
        ),
    ]
