# Generated by Django 5.0.6 on 2024-07-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bot', '0004_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
