# Generated by Django 5.0.6 on 2024-07-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bot', '0005_alter_interests_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
