# Generated by Django 5.0.6 on 2024-07-24 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bot', '0010_alter_user_liked_alter_user_not_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delay_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='all_users', to='api_bot.interests'),
        ),
    ]
