# Generated by Django 5.0.6 on 2024-07-24 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bot', '0011_user_delay_users_alter_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delay_users',
            field=models.ManyToManyField(blank=True, related_name='who_skip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='who_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
